kind: pipeline
name: kernel_santoni

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: Compile
    image: ubuntu:rolling
    commands:
      - apt-get -y update && apt-get -y install bc build-essential bison python2 zip unzip curl git wget zstd
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/zeta96/kernelci/master/L_drone_gcc_s)"
    when:
      branch:
        - LA.UM.8.6.r1/skybase
