kind: pipeline
name: kernel_santoni

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: Compile
    image: fedora:latest
    commands:
      - dnf update && dnf groupinstall "Development Tools" "C Development Tools and Libraries" && dnf install bash python2 zip unzip xz curl wget && yes
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/zeta96/kernelci/master/L_drone_gcc_s)"
    when:
      branch:
        - LA.UM.8.6.r1/skybase
